### ISSUE TITLE
package.path incorrect?

### ISSUE THREAD

**Issue by clementfarabet** [torch/luajit-rocks#13]
I've just started to re-activate LuaJIT for some experiment stuff, and came across a weirdness:

```
-- package.path for Lua:          
./?.lua;/Users/cfarabet/tmp/share/lua/5.1/?.lua;/Users/cfarabet/tmp/share/lua/5.1/?/init.lua;/Users/cfarabet/tmp/lib/lua/5.1/?.lua;/Users/cfarabet/tmp/lib/lua/5.1/?/init.lua
    
-- package.path for LuaJIT:
./?.lua;/Users/cfarabet/tmp/share/luajit-2.0.3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/Users/cfarabet/tmp/share/lua/5.1/?.lua;/Users/cfarabet/tmp/share/lua/5.1/?/init.lua

```

Why would LuaJIT include `/usr/local...` in its path? Causes some pretty hectic library loading.

**Comment by soumith** [comment]
seems like it's some kind of default. clearly seems wrong.

**Comment by soumith** [comment]
let me know if it's still the case. LuaJIT and luarocks have been updated several times after that.
