### ISSUE TITLE
normal exit is not clean

### ISSUE THREAD

**Issue by mavenlin** [torch/luajit-rocks#16]
A bug in luajit.
When executing the following,
```
torch.Tensor.__gc = function() print('gc') end
tensor = torch.Tensor(10)
-- tensor = nil
-- collectgarbage()
```
at exit 'gc' will not be printed, however when the last two lines of code are uncommented it will print 'gc'.
Which means at exit collectgarbage is not called by the interpreter.
It is a problem when gc writes log to files, or gc disconnects from a server.

@soumith What's your opinion on this?

**Comment by soumith** [comment]
@mavenlin it is interesting, and it is a bug in the trepl interpreter (not a bug in luajit).

For example, if you run the script with:
luajit [script.lua]
, you will see that it prints out "gc".
If you run the same with:
th [script.lua]
you dont see the print.

What's the use-case where you ran into this bug? It is likely something minor and not concerning to anything practically relevant.

**Comment by mavenlin** [comment]
@soumith In my case I wrapped the parameter server as userdata, gc calls the destructor in C++ side, which notifies the server side of the exit. If it is not gced the server is never notified.

**Comment by soumith** [comment]
fixed the issue via https://github.com/torch/trepl/pull/38
Updating your trepl via: "luarocks install trepl" will solve the issue.
I'm updating distro to have this latest fix as well.

Thanks a lot for the report.
