### ISSUE TITLE
luajit 2.1.0 beta

### ISSUE THREAD

**Issue by eulerreich** [torch/luajit-rocks#18]
luajit 2.1.0 beta has been released some time ago. Are there plans to package it?

**Comment by andresy** [comment]
it is in there... cmake with -DLUAJIT21=1

**Comment by soumith** [comment]
@andresy he means luajit 2.1 beta. We have luajit 2.1 alpha, several commits behind.

**Comment by soumith** [comment]
ooooh, i see you just updated it . nice!

**Comment by andresy** [comment]
yes :)
